#include "game.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "gba.h"

//images
#include "images/garbage.h"
#include "images/buzz.h"
#include "images/tower1.h"
#include "images/tower2.h"
#include "images/tower3.h"
#include "images/startscreen.h"
#include "images/gameover.h"
#include "images/background.h"
#include "images/ground.h"

// Author: Saumya Jain

/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.

typedef enum {
  START,
  START_NO_DRAW,
  PLAY,
  GAMEOVER,
} GBAState;

Buzz gameBuzz = {80, 15, 26, 26};
Tower gameTower1 = {81, 180, tower1, 68, 34};
Ground gameGround = {150, 0, ground, 24, 240};
volatile int points = 0;
volatile int speed = 2;

int detectCollision(void);

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;
  int frameCount = 0;
  int started = 0;

  while (1) {
    frameCount++;
    currentButtons = BUTTONS;  // Load the current state of the buttons

    if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
      state = START; // if backspace pressed, go back to beginning
      speed = 2;
      points = 0;
      gameBuzz.r = 80;
      gameBuzz.c = 15;
      gameTower1.c = 180;
      gameTower1.image = tower1;
      gameTower1.width = 34;
    }


    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {

      //done
      case START:
        waitForVBlank();
        drawFullScreenImageDMA(startscreen);
        drawString(80, 20, "Press Up", BLUE);
        drawString(90, 25, "to play", BLUE);
        state = START_NO_DRAW;
        break;

      //done
      case START_NO_DRAW:
        if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
          //perfect
          drawFullScreenImageDMA(background);
          //perfect
          drawImageDMA(gameBuzz.c, gameBuzz.r, 26, 26, buzz);
          //perfect
          drawImageDMA(0, 150, 240, 24, ground);
          //perfect
          drawImageDMA(gameTower1.c, gameTower1.r, gameTower1.width, gameTower1.height, gameTower1.image);
          //perfect
          drawString(20, 80, "Score: 0", BLACK);
          state = PLAY;
        }
        break;

      //tofix
      
      case PLAY:
        if (detectCollision()) {
            state = GAMEOVER;
            break;
        }
        waitForVBlank();
        if (started) {
          drawBackDMA(gameTower1.c + gameTower1.width - speed, gameTower1.r, speed, gameTower1.height, background);
            //make sure this works
            gameTower1.c -= speed;

          if (points == 5 && speed == 2) {
            gameTower1.image = tower2;
            gameTower1.height = 80;
            gameTower1.width = 40;
            gameTower1.r = 70;
            speed++;
          }
          if (points == 10 && speed == 3) {
            gameTower1.image = tower3;
            gameTower1.height = 89;
            gameTower1.width = 45;
            gameTower1.r = 60;
            speed++;
          }
          if (gameTower1.c < 1) {
            //check the following 2
              drawBackDMA(gameTower1.c, gameTower1.r, gameTower1.width, gameTower1.height , background);
              drawBackDMA(80, 20, 60, 8, background);
              points++;
              char buffer[128];
              snprintf(buffer,128,"Score: %d", points);
              drawString(20, 80, buffer, BLACK);
              gameTower1.c = 180;
          }
          drawImageDMA(gameTower1.c, gameTower1.r, gameTower1.width, gameTower1.height, gameTower1.image);
        }
        if (KEY_JUST_PRESSED(BUTTON_UP, currentButtons, previousButtons) ) {
          started = 1;
          //check
          drawBackDMA(gameBuzz.c, gameBuzz.r, 26, 26, background);
            gameBuzz.r -= 80;
          drawImageDMA(gameBuzz.c, gameBuzz.r, 26, 26, buzz);
        } else {
          //check
          drawBackDMA(gameBuzz.c, gameBuzz.r, 15, 3, background);
          gameBuzz.r += 2;

          if (gameBuzz.r < 0) {
            // preventing gt from leaving the screen
            gameBuzz.r = 0;
          }
          drawImageDMA(gameBuzz.c, gameBuzz.r, 26, 26, buzz);
        }
      break;

      case GAMEOVER:
        waitForVBlank();
        drawFullScreenImageDMA(gameover);
        char bufferer[128];
        snprintf(bufferer,128,"%d", points);
        drawString(80, 1, "Score: ", RED);
        drawString(100, 1, bufferer, RED);
      break;
    }
    previousButtons = currentButtons;  // Store the current state of the buttons
  }
  return 0;
}

int detectCollision(void) {
    int x1 = gameBuzz.c;
    int x2 = gameBuzz.c + BUZZ_WIDTH;
    int y1 = gameBuzz.r;
    int y2 = gameBuzz.r + BUZZ_HEIGHT;

    int towX1 = gameTower1.c;
    int towX2 = gameTower1.c + gameTower1.width;
    int towY1 = gameTower1.r;
    int towY2 = gameTower1.r + gameTower1.height;

    //int groundX1 = gameGround.c;
    //int groundX2 = gameGround.c + gameGround.width;
    //int groundY1 = gameGround.r;
    int groundY2 = gameGround.r + gameGround.height;
    
    //tech tower collisions
    if ((x1 >= towX1 && x1 <= towX2) && (y1 >= towY1 && y1 <= towY2))
      return 1;
    else if ((x2 >= towX1 && x2 <= towX2) && (y2 >= towY1 && y2 <= towY2))
      return 1;
    else {
      if ((towX1 >= x1 && towX1 <= x2) && (towY1 >= y1 && towY1 <= y2))
        return 1;
      else if ((towX2 >= x1 && towX2 <= x2) && (towY2 >= y1 && towY2 <= y2))
        return 1;
    }

    //ground collisions
    if (y1 >= groundY2) {
      return 1;
    }

    return 0;
}
